In [1]:


import numpy as np 

In [7]:
r = np.random.random((5,5))
r

array([[0.38957235, 0.6329831 , 0.46142114, 0.63494721, 0.22394569],
       [0.382349  , 0.37431609, 0.77108318, 0.79080495, 0.64196141],
       [0.95305575, 0.55507769, 0.7337881 , 0.02050745, 0.13904002],
       [0.83077129, 0.75842611, 0.20659913, 0.99312752, 0.36492303],
       [0.42568258, 0.27555471, 0.0921857 , 0.88537593, 0.34089178]])

In [11]:
np.mean([0.38957235, 0.382349, 0.95305575, 0.83077129, 0.42568258] )

np.float64(0.5962861939999999)

In [10]:
np.mean([0.38957235, 0.6329831 , 0.46142114, 0.63494721, 0.22394569])

np.float64(0.468573898)

In [17]:
m1 = 0
for a in r:
    m1 += np.mean(a)

print(m1/r.shape[0])

0.5281556753862429


In [13]:
m1/r.shape[0]

array([0.31918236, 0.56164046, 0.62658176, 0.50434725, 0.39820378])

In [9]:
np.mean(r, axis=0)

array([0.59628619, 0.51927154, 0.45301545, 0.66495261, 0.34215239])

In [12]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

c:\Users\matte\.pyenv\myenv\.rag\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [24]:
e = model.encode('''dnjcnj jdncdjcncj djcjcdjdc kdkdkd dkjkdddddddddddddddddddddddddd bonjour je suis There's still time to share your experience with Standard Bus by Mogador, booked through Bookaway.

Your feedback helps us improve and guides other travelers to make great choices.

It only takes a minute—rate your ride now:''')

In [25]:
e.shape

(384,)

In [26]:
np.zeros_like(r)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
def test(r):
    r[0,1] = 4

In [28]:
test(r)

In [29]:
r

array([[0.38957235, 4.        , 0.46142114, 0.63494721, 0.22394569],
       [0.382349  , 0.37431609, 0.77108318, 0.79080495, 0.64196141],
       [0.95305575, 0.55507769, 0.7337881 , 0.02050745, 0.13904002],
       [0.83077129, 0.75842611, 0.20659913, 0.99312752, 0.36492303],
       [0.42568258, 0.27555471, 0.0921857 , 0.88537593, 0.34089178]])

In [30]:
r[:, 0]

array([0.38957235, 0.382349  , 0.95305575, 0.83077129, 0.42568258])

In [37]:
r1, r2 = np.random.random((5,5)), np.random.random((5,5))
rs = r1 + r2 
rs

array([[1.08628695, 1.34245011, 0.73307082, 1.43391548, 1.2117914 ],
       [0.77740525, 0.76826792, 1.32586955, 1.10724274, 1.55951274],
       [1.05777355, 1.03525589, 0.98502784, 1.08509637, 1.29889869],
       [0.96838627, 1.45059311, 1.09188814, 0.12282293, 0.88962316],
       [0.23215636, 0.93745785, 1.44435634, 0.59627953, 1.2705795 ]])

In [39]:
r1_ = np.sum(r1, axis=0)
r1_

array([2.71385488, 3.37596311, 3.1512628 , 2.06190508, 2.4940295 ])

In [40]:
r2_ = np.sum(r2, axis=0)
r2_

array([1.40815349, 2.15806177, 2.42894988, 2.28345198, 3.73637599])

In [42]:
(r1_ + r2_)/5

array([0.82440167, 1.10680498, 1.11604254, 0.86907141, 1.2460811 ])

In [43]:
np.mean(rs, axis=0)

array([0.82440167, 1.10680498, 1.11604254, 0.86907141, 1.2460811 ])

In [35]:
np.mean(r, axis=0)

array([0.59628619, 1.19267492, 0.45301545, 0.66495261, 0.34215239])